version: 2

before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run ./cmd/wt completion bash > completions/wt.bash"
    - sh -c "go run ./cmd/wt completion zsh > completions/_wt"
    - sh -c "go run ./cmd/wt completion fish > completions/wt.fish"

builds:
  - main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: "âœ¨ Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "ðŸ› Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "ðŸ“š Documentation"
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: "ðŸ”§ Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: raphi011
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/raphi011/wt"
    description: "Git worktree manager with GitHub PR integration"
    license: "MIT"
    dependencies:
      - name: git
    extra_install: |
      bash_completion.install "completions/wt.bash" => "wt"
      zsh_completion.install "completions/_wt"
      fish_completion.install "completions/wt.fish"
