version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: "✨ Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: "🔧 Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: raphi011
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/raphi011/wt"
    description: "Git worktree manager with GitHub PR integration"
    license: "MIT"
    install: |
      bin.install "wt"
    test: |
      system "#{bin}/wt", "--version"
