coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "cmd/wt/*_integration_test.go"
  - "cmd/wt/completions.go"
